#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo 'Styling, testing and building project before committing'

npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)
npm run check-lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)
npm run check-types ||
(
    echo 'Failed Type check.'
    false;
)
npm run build ||
(
    echo 'Remix build failed: View the errors above to see why.'
    false;
)
echo 'Committing... '